#!/usr/bin/env bash	
export TITLE="$1"
export TAGS="$2"
export DATE="$(date +"%b %e, %Y")"
. ../lib/mo # loads the "mo" function
cat << EOF | mo --source=env.vars
---
title: {{TITLE}}
date: {{DATE}}
tags: {{TAGS}}
...

# {{TITLE}}

user, {{USER}}
shell, {{SHELL}}
browser, {{BROWSER}}
terminal, {{TERMINAL}}
reader, {{READER}}
editor, {{EDITOR}}
url launcher, {{URL_LAUNCHER}}
music player, {{MUSIC_PLAYER}}
player, {{VIDEO}}
wm, {{WM}}
file manager, {{FILE}}
image viewer, {{IMAGE}}
mail client, {{MAIL_CLIENT}}
os, {{OS}}
newsreader, {{NEWSREADER}}
pager, {{PAGER}}
calendar, {{CALENDAR}}

EOF
