#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

export CMD=( init list backlinks new open sync show push preview tags help )
source "${0%/*}"/lib/mo
cat << EOF | mo
usage: zit COMMAND

available commands:
{{#CMD}}
  {{.}}
{{/CMD}}

use "zit help COMMAND" for more information about a command.
EOF
