#!/usr/bin/env bash
IFS=$'\n\t'

export ID="$(date +%Y%m%d%H%M%S)"
export TITLE="${1:-new-zettel}"
export DATE="$(date +"%B %d, %Y")"
export TAGS="$(date +%Y)"

. ../lib/mo # loads the "mo" function
cat << EOF | mo --source=env.vars
---
id: {{ID}}
title: {{TITLE}}
date: {{DATE}}
tags: {{TAGS}}
---

# {{TITLE}}


EOF

# python3.9 ../zet.py

