#!/usr/bin/env bash
IFS=$'\n\t'

TITLE="${1:-new-zet}"
TAGS="${2:-}"
DATE="$(date +"%b %e, %Y")"
DEFAULT_COMMAND="${DEFAULT_COMMAND:-help}"

. lib/mo # loads the "mo" function
cat << EOF | mo
---
title: {{TITLE}}
date: {{DATE}}
tags: {{TAGS}}
---

# {{TITLE}}


EOF
