#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

export zettel_id_format="$(date +%Y%m%d%H%M%S)"
export zettel_title="${1:-new-zettel}"
export zettel_date_format="$(date +"%B %d, %Y")"
export zettel_tag_format="$(date +%Y)"

ZET_ID="${zettel_id_format}"
ZET_TITLE="${zettel_title}"
ZET_DATE="${zettel_date_format}"
ZET_TAGS="${zettel_tag_format}"

source "${0%/*}"/lib/mo
cat <<EOF | mo
---
id: {{ZET_ID}}
title: {{ZET_TITLE}}
date: {{ZET_DATE}}
tags: {{ZET_TAGS}}
---

# {{ZET_TITLE}}


EOF
