#!/usr/bin/env bash
IFS=$'\n\t'

export ID="$(date +%Y%m%d%H%M%S)"
export TITLE="${1:-new-zettel}"
export DATE="$(date +"%B %d, %Y")"
export TAGS="$(date +%Y)"

. ./lib/mo
cat << EOF | mo
---
id: {{ID}}
title: {{TITLE}}
date: {{DATE}}
tags: {{TAGS}}
---

# {{TITLE}}


EOF

