name: ci
on:
  push:
    branch:
      - main
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run shellcheck
      uses: ludeeus/action-shellcheck@master
